name: build latest package
runs:
  using: "Composite"
  steps:
  - name: Prepare a package
    shell: bash
    run: |
      npm install
      npm run build
      git fetch origin latest
      git worktree add ../latest latest
      cp -r dist/ ../latest/
      cp action.yml ../latest/
