name: build latest package
runs:
  using: "Composite"
  steps:
  - name: Prepare a package
    run: |
      npm install
      npm run build
      git worktree add latest
      cp -r dist/ latest/
      cp action.yml latest/
      cp package.json latest/
