name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

env:
  HEROKU_EMAIL: ${{ vars.HEROKU_EMAIL }}
  HEROKU_PROJ_PREFIX: "kuboon-deploy-test"
  HEROKU_APP_NAME:
jobs:
  deploy-test-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "HEROKU_APP_NAME=${{ env.HEROKU_PROJ_PREFIX }}-1" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
      - run: npm run setup tests/test-1/data.json
      - run: |
          git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
          git config --global user.name $GITHUB_ACTOR
          git add -A
          git commit -m "Added data.json"
      - id: heroku-deploy
        uses: ./../latest
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ env.HEROKU_EMAIL }}
          appdir: "tests/test-1"
          env_file: ".env"
          delay: 5
        env:
          HD_CHECK: "true"
      - run: npm run test-action https://${{ steps.heroku-deploy.outputs.app_domain }}/

  deploy-test-2:
    runs-on: ubuntu-latest
    needs: deploy-test-1
    steps:
      - run: echo "HEROKU_APP_NAME=${{ env.HEROKU_PROJ_PREFIX }}-2" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
      - run: npm run setup tests/test-2/home.html
      - id: heroku-deploy
        uses: ./../latest
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ env.HEROKU_EMAIL }}
          appdir: "tests/test-2"
          delay: 5
      - run: npm run test-action https://${{ steps.heroku-deploy.outputs.app_domain }}/

  deploy-test-3:
    runs-on: ubuntu-latest
    needs: deploy-test-2
    steps:
      - run: echo "HEROKU_APP_NAME=${{ env.HEROKU_PROJ_PREFIX }}-3" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
      - run: npm run setup tests/test-3/data.json
      - id: heroku-deploy
        uses: ./../latest
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ env.HEROKU_EMAIL }}
          appdir: "tests/test-3"
          usedocker: true
      - run: npm run test-action https://${{ steps.heroku-deploy.outputs.app_domain }}/

  deploy-test-4:
    runs-on: ubuntu-latest
    needs: deploy-test-3
    steps:
      - run: echo "HEROKU_APP_NAME=${{ env.HEROKU_PROJ_PREFIX }}-1" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: ./.github/actions/package
      - run: npm run setup tests/test-4/data.json
      - id: heroku-deploy
        uses: ./../latest
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ env.HEROKU_APP_NAME }}
          heroku_email: ${{ env.HEROKU_EMAIL }}
          appdir: "tests/test-4"
          healthcheck: "/health"
          checkstring: "ok"
          procfile: "web: gunicorn index:app"
      - run: npm run test-action https://${{ steps.heroku-deploy.outputs.app_domain }}/
